INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (1, 'Alabama', 'AL');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (2, 'Alaska', 'AK');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (3, 'Arizona', 'AZ');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (4, 'Arkansas', 'AR');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (5, 'California', 'CA');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (6, 'Colorado', 'CO');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (7, 'Connecticut', 'CT');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (8, 'Delaware', 'DE');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (9, 'Florida', 'FL');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (10, 'Georgia', 'GA');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (11, 'Hawaii', 'HI');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (12, 'Idaho', 'ID');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (13, 'Illinois', 'IL');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (14, 'Indiana', 'IN');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (15, 'Iowa', 'IA');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (16, 'Kansas', 'KS');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (17, 'Kentucky', 'KY');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (18, 'Louisiana', 'LA');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (19, 'Maine', 'ME');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (20, 'Maryland', 'MD');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (21, 'Massachusetts', 'MA');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (22, 'Michigan', 'MI');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (23, 'Minnesota', 'MN');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (24, 'Mississippi', 'MS');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (25, 'Missouri', 'MO');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (26, 'Montana', 'MT');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (27, 'Nebraska', 'NE');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (28, 'Nevada', 'NV');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (29, 'New Hampshire', 'NH');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (30, 'New Jersey', 'NJ');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (31, 'New Mexico', 'NM');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (32, 'New York', 'NY');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (33, 'North Carolina', 'NC');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (34, 'North Dakota', 'ND');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (35, 'Ohio', 'OH');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (36, 'Oklahoma', 'OK');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (37, 'Oregon', 'OR');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (38, 'Pennsylvania', 'PA');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (39, 'Rhode Island', 'RI');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (40, 'South Carolina', 'SC');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (41, 'South Dakota', 'SD');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (42, 'Tennessee', 'TN');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (43, 'Texas', 'TX');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (44, 'Utah', 'UT');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (45, 'Vermont', 'VT');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (46, 'Virginia', 'VA');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (47, 'Washington', 'WA');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (48, 'West Virginia', 'WV');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (49, 'Wisconsin', 'WI');
INSERT INTO State_Key (StateID, State, Abbreviation) VALUES (50, 'Wyoming', 'WY');